#!/usr/bin/env bash

# Halt on error and support tracing.
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

# Find and read configuration file.
# shellcheck source=commands
source "$(dirname "$(realpath "${BASH_SOURCE[0]}")")/config"

# Extract the command that was issued.
COMMAND="${1#$PLUGIN_COMMAND_PREFIX:}"
shift 1

# Subcommand switcher.
case "$COMMAND" in
    report|"")
        "$PLUGIN_BASE_PATH/subcommands/report"
        ;;
    install)
        "$PLUGIN_BASE_PATH/subcommands/install" "$@"
        ;;
    restore)
        "$PLUGIN_BASE_PATH/subcommands/restore"
        ;;
    install-template)
        "$PLUGIN_BASE_PATH/subcommands/install-template" "$@"
        ;;
    restore-template)
        "$PLUGIN_BASE_PATH/subcommands/restore-template"
        ;;
    help)
        "$PLUGIN_BASE_PATH/subcommands/help"
        ;;
    *)
        exit "$DOKKU_NOT_IMPLEMENTED_EXIT"
        ;;
esac
