#!/usr/bin/env bash

# Halt on error and support tracing.
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

# Load dokku/common API.
# shellcheck source=/dev/null
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"

# Figure out plugin name, because apparently that's an odd information for dokku to provide.
PLUGIN_NAME="$(basename "$(dirname "$(realpath "${BASH_SOURCE[0]}")")")"
export PLUGIN_NAME

# Read configuration file.
# shellcheck source=post-extract
source "$PLUGIN_ENABLED_PATH/$PLUGIN_NAME/config"

# APP="$1"
TMP_WORK_DIR="$2"
GLOBAL_TEMPLATE_FILE="$NGINX_CONFIG_ROOT/nginx.conf.sigil"

# If the application aready has a template in its repository, bail.
if [ -f "$GLOBAL_TEMPLATE_FILE" ]; then
    if [ -f "$TMP_WORK_DIR/nginx.conf.sigil" ]; then
        dokku_log_info1 "nginx.conf.sigil already present in app."
    else
        cp "$GLOBAL_TEMPLATE_FILE" "$TMP_WORK_DIR/nginx.conf.sigil"
        dokku_log_info1 "Custom nginx.conf.sigil deployed."
    fi
fi