#!/usr/bin/env bash

# Halt on error and support tracing.
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

help() {
	cat <<-EOF
		    $PLUGIN_COMMAND_PREFIX:help, Display usage details
		    $PLUGIN_COMMAND_PREFIX:install <repository>, Save nginx config files and clone given repository in its place
		    $PLUGIN_COMMAND_PREFIX:report, [NOT IMPLEMENTED] Report about current nginx config
		    $PLUGIN_COMMAND_PREFIX:restore, [NOT IMPLEMENTED] Restore original nginx config files
	EOF
}

if [ "$1" = "--no-usage" ]; then
	help
else
	cat <<-EOF
		Usage: dokku $PLUGIN_COMMAND_PREFIX:subcommand ...

		Subcommands:
	EOF
	help | sort | column -c2 -t -s,
fi
